---
  - name: Install Packages on CentOS and Ubuntu
    hosts: all
    vars:
      custom: pwd
      packages: 
        - vim
        - curl
        - wget
        - git
        - tree
    gather_facts: yes
    tasks:
      - name: Install packages on CentOS
        when: ansible_facts['distribution'] == "CentOS"
        yum:
          name: "{{ packages }}"
          state: latest
      
      - name: Install packages on Ubuntu
        when: ansible_facts['distribution'] == "Ubuntu"
        apt:
          name: "{{ packages }}"
          state: latest
      
      - name: Run a task 
        shell:
          cmd: "{{ custom }}"