---
  - name: Apache Installation 
    hosts: dev
    gather_facts: yes
    tasks:
      - name: Install Apache
        when: 
        - ansible_facts['distribution'] == "CentOS"
        yum:
          name: httpd
          state: latest
      
      - name: Copy Index.html
        when: 
        - ansible_facts['distribution'] == "CentOS"
        copy:
          dest: /var/www/html/
          src: index.html
        register: copy_result
      
      - name: Start and Restart Apache
        when:
        - ansible_facts['distribution'] == "CentOS"
        - copy_result is changed
        systemd:
          name: httpd
          state: restarted
          enabled: yes